input {
  beats { port => 5044 }
  tcp { port => 5000 codec => json_lines }
  udp { port => 5000 codec => json }
}

filter {
  if ![service][name] and [service_name] {
    mutate { add_field => { "[service][name]" => "%{service_name}" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
}

